WaadManager/WaadManager.Web/Controllers/ProgrammeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaadManager.GraphStore;
using WaadManager.GraphStore.Models;

namespace WaadManager.Web.Controllers
{
    public class ProgrammeController : AbstractBaseController
    {
        AdGraphClient client = new AdGraphClient();

        public ActionResult ViewSchedule()
        {
            var sched = client.GetConfSchedule();
            var faves = client.GetFavourites(GetCurrentUpn(), string.Empty);
            sched.UpdateFavourites(faves.Values);

            //split into days for UI
            ViewBag.events14 = sched.Values.Where(e => e.Day.Substring(0, 2) == "14");
            ViewBag.events15 = sched.Values.Where(e => e.Day.Substring(0, 2) == "15");
            ViewBag.events16 = sched.Values.Where(e => e.Day.Substring(0, 2) == "16");
            ViewBag.events17 = sched.Values.Where(e => e.Day.Substring(0, 2) == "17");

            ViewBag.Schedule = sched;
            ViewBag.IsSpeaker = IsSpeaker();
            return View();
        }

        public ActionResult ViewFavourites()
        {
            var sched = client.GetConfSchedule();
            var faves = client.GetFavourites(GetCurrentUpn(), string.Empty);
            sched.UpdateFavourites(faves.Values);
            sched.Values = sched.Values.Where(e => e.IsFave);

            ViewBag.events14 = sched.Values.Where(e => e.Day.Substring(0, 2) == "14");
            ViewBag.events15 = sched.Values.Where(e => e.Day.Substring(0, 2) == "15");
            ViewBag.events16 = sched.Values.Where(e => e.Day.Substring(0, 2) == "16");
            ViewBag.events17 = sched.Values.Where(e => e.Day.Substring(0, 2) == "17");

            ViewBag.Schedule = sched;
            ViewBag.IsSpeaker = IsSpeaker();
            return View();
        }

        public ActionResult ViewMyEngagements()
        {
            var sched = client.GetConfSchedule();
            var username = GetCurrentEmailAddress();
            sched.Values = sched.Values.Where(s => !string.IsNullOrWhiteSpace(s.Speakers) && s.Speakers.Contains(username));
            
            ViewBag.events14 = sched.Values.Where(e => e.Day.Substring(0, 2) == "14");
            ViewBag.events15 = sched.Values.Where(e => e.Day.Substring(0, 2) == "15");
            ViewBag.events16 = sched.Values.Where(e => e.Day.Substring(0, 2) == "16");
            ViewBag.events17 = sched.Values.Where(e => e.Day.Substring(0, 2) == "17");
            
            ViewBag.Schedule = sched;
            ViewBag.IsSpeaker = IsSpeaker();
            return View();
        }

        public ActionResult AddAsFavourite(string eventCode)
        {
            var fav = new Favourite();
            fav.Upn = GetCurrentUpn();
            fav.EventCode = eventCode;
            client.CreateFavourite(fav);
            return new EmptyResult();
        }

        public ActionResult RemoveFavourite(string eventCode)
        {
            client.DeleteGPTuple(GetCurrentUpn(), eventCode);
            return new EmptyResult();
        }
    }
}

WaadManager/WaadManager.Web/Views/Shared/_Buttons.cshtml
<input type="button" value="Schedule" onclick="window.location.href='@Url.Action("ViewSchedule", "Programme")';"/>
<input type="button" value="Favourites" onclick="window.location.href='@Url.Action("ViewFavourites", "Programme")';"/>

@if (ViewBag.IsSpeaker != null && ViewBag.IsSpeaker)
{
    <input type="button" value="Engagements" onclick="window.location.href='@Url.Action("ViewMyEngagements", "Programme")';"/>
}

WaadManager/WaadManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - European Identity and Cloud Conference Agenda Web site</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div style ="margin-left:70px;">
                    <a href="@Url.Action("Index", "Home")">
                        <img src="@Url.Content("~/Images/header-logo-idconf.png")" width="240" height="40"/>
                    </a>
                    <section id="login" style="float:right;">
                        @Html.Partial("_LoginPartial")
                    </section>
                </div>
            </div>
            <div style="display:none;">
                <nav style="margin-left:auto; margin-right:auto;">
                    <ul id="menu">
                        <li style="padding-left: 0px;">@Html.ActionLink("HOME", "Index", "Home")</li>
                    </ul>
                </nav>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                <div style="width:90%; margin-left:20px; margin-bottom: 20px;">
                    @RenderBody()
                </div>
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <!--<p>&copy; @DateTime.Now.Year - Release Mobile Ltd</p>-->
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>